Add current working draft of rendering summary
bevyengine/bevy-website pull request #1080
Opened 2024-03-08 02:06 UTC by NthTensor

This PR adds a summary of the bevy's rendering crates as of 0.13. It is a work in process, and absolutely contains omissions or mistakes. Please let me know if you find any. Feedback on both content and presentation is welcome! 

The goal is to cover the most important aspects of `bevy_render`, `bevy_core_pipeline` and `bevy_pbr` in order. Each crate is discussed in isolation, using only concepts introduced by it's dependencies. When this is complete (hopefully well before 0.14), I'd like to split this content up between the bevy book and the module docs of the relevant crates.

2024-03-08 14:35 UTC, NthTensor commented
Do docs editors have a preference on filled vs unfilled paragraphs?

2024-03-08 15:58 UTC, alice-i-cecile commented
Overall feelings: really useful, not particularly user-approachable. I'll chew on the best way to digest this information into a format that matches the rest of the book.

> Do docs editors have a preference on filled vs unfilled paragraphs?

Not currently no.

2024-04-01 20:02 UTC, andriyDev commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +  `wgpu_native` and the browser's own `WebGpu` adapter, etc.)m
Extra m

2024-04-01 20:03 UTC, andriyDev commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +[`wgpu::Adapter`] and [`wgpu::Device`]. The adapter provides access the platform
"The adapter provides access **to** the platform..."

2024-04-01 20:03 UTC, andriyDev commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +ultimately what allows us to is submit work to the GPU.
Extra "is"

2024-04-01 20:10 UTC, andriyDev commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +1. The `WebGPU` api provided by `wgpu`,
This is my personal preference but I think we should reverse this list. For one, it's written from highest to lowest level, but the numbers go from lowest to highest. Also the abstraction feels less "obvious" in this order. As in, I think it makes more sense to say "start from the physical GPU, and slowly make it less and less specific". Maybe that's just me.

If you change the, make sure to renumber the references to the layers in following paragraphs!

2024-04-01 20:11 UTC, andriyDev commented
Ahhhh so sorry for the spam, I intended to start a review! 🤦‍♂️

2024-04-01 20:13 UTC, NthTensor commented
> Ahhhh so sorry for the spam

I appreciate the help no matter the format!

2024-04-03 07:29 UTC, andriyDev requested changes
Ok I've now finished my first pass. I've of course ignored all the TODO sections.

2024-04-03 07:29 UTC, andriyDev commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +The main thing `bevy_core_pipleline` does is add two new subgraphs to the render
"pipeline"

2024-04-21 01:39 UTC, NthTensor commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +Buffers, Texture Views and Samplers (as well as arrays of the same) can be
I ended up just redrafting this section. Your feedback was super helpful here especially.

2024-04-21 01:52 UTC, NthTensor commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +## `bevy_ecs` Preliminaries
I'm going to leave this in for now, but I agree it should be moved or deleted eventually.

2024-04-21 02:09 UTC, NthTensor commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +With knowledge of subgraphs and views under our belt, we can approach one of the
I'll make a note to come back to this.

2024-04-21 02:19 UTC, NthTensor commented
Thank you so much! I've addressed your feedback. Going to start filling in some more of the TODO sections, and making notes for new topics to cover for the 0.14 release.

2024-05-19 21:24 UTC, SIGSTACKFAULT requested changes
Obligatory half of these are IMHO

2024-05-19 21:24 UTC, SIGSTACKFAULT commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +programmable stages of pipelines. They are written in a language `WGSL`.
"They are written in the [`WGSL`](https://www.w3.org/TR/WGSL/) language"

link to https://www.w3.org/TR/WGSL/ or maybe the book page on it

2024-05-19 21:24 UTC, SIGSTACKFAULT commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +from bevy ECS commands.
"bevy ECS commands" needs link. also Bevy should be capitalized.

2024-05-19 21:24 UTC, SIGSTACKFAULT commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +transmit a response. We'll reffer to these as GPU commands to differentiate them
put "GPU commands" in quotes or italics maybe.

2024-05-19 21:24 UTC, SIGSTACKFAULT commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +As covered in the `wgpu` preliminary, rendering involves queuing render commands
add internal link back to the wgpu preliminary header

2024-05-19 21:24 UTC, SIGSTACKFAULT commented on content/learn/book/graphics/rendering-internals/technical-summary.md
> +users should attempt to keep systems the extract schedule small.
missing an "in"

2025-05-16 16:02 UTC, TimJentzsch commented
Added the adopt me label, as it has been stale for over a year

2025-05-16 21:28 UTC, closed without merging