Cancel in progress CI jobs on PRs
bevyengine/bevy-website pull request #1084
Opened 2024-03-09 03:43 UTC by TrialDragon

At the moment if you commit multiple times to a PR while CI is still going it takes up the amount of jobs that can be run at once. Instead we should cancel in progress jobs on new pushes to a PR.

2024-03-10 01:48 UTC, BD103 requested changes
Similar PR in the main Bevy repository: https://github.com/bevyengine/bevy/pull/11130

I'm personally for this change, since the less time an action runner spends doing a specific job means the more jobs in total it can do. I have a few requested changes, but they're non-blocking since they only add comments and formatting.

2024-03-10 01:48 UTC, BD103 commented on .github/workflows/ci.yml
> +  cancel-in-progress: ${{github.event_name == 'pull_request'}}
```suggestion
concurrency:
  # Only the same workflows on the same branch can cancel each other.
  group: ${{ github.workflow }}-${{ github.ref }}
  # Only cancel runs in a PR; we don't want to cancel commit checks on main.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
```

2024-03-10 02:11 UTC, BD103 approved these changes

2024-03-19 00:45 UTC, BD103 commented
@mockersf would you mind reviewing this?

2024-05-01 23:32 UTC, ickk approved these changes
Looks like a straight forward implementation of github actions [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency). 

Might help keep things moving in CI at times when lots is happening, such as release-prep

2024-05-03 02:06 UTC, merged