Help users discover the correct version of the official examples
bevyengine/bevy-website pull request #109
Opened 2021-03-11 21:55 UTC by jamadazi

1. Change all links to point to the `latest` branch
2. Explicitly instruct users to `git checkout` the correct version when they clone the repo to run the examples
  - I suspect this "getting started" book page was a big cause of misdirected/confused new users
  - I intend to make a similar change to the README in the bevy repo, to make it clear how to run the correct examples
3. Add a card on the `Learn` page linking to the examples

2021-03-11 22:01 UTC, memoryruins requested changes

2021-03-11 22:01 UTC, memoryruins commented on templates/learn.html
> +  <a class="card" href="https://github.com/bevyengine/bevy/tree/latest/examples">
```suggestion
  <a class="card" href="https://github.com/bevyengine/bevy/tree/latest/examples#examples">
```
with a similar motivation as #69

2021-03-11 22:12 UTC, jamadazi commented on content/learn/book/getting-started/_index.md
> +4. Try the examples in the [examples folder](https://github.com/bevyengine/bevy/tree/latest/examples)
This link already points to `latest`, which is a new git branch that cart created to always point to the latest *release*. This lets us have links that direct users to the right version without them going stale.

I don't think we need to do this.

@cart should give his opinion about which link he prefers.

2021-03-11 23:02 UTC, memoryruins commented on content/learn/book/getting-started/_index.md
> +4. Try the examples in the [examples folder](https://github.com/bevyengine/bevy/tree/latest/examples)
I think there is a benefit to leading the users to the instructions and table of contents before they dive into the folders, especially when some of the examples have specific build instructions.

2021-03-11 23:05 UTC, memoryruins commented on content/learn/book/next-steps/_index.md
> +* **[The Bevy Examples](https://github.com/bevyengine/bevy/tree/latest/examples#examples)**: We create an example for every major Bevy feature. This is currently the best way to learn Bevy's features
This link continues to use `#examples` at the end, so if https://github.com/bevyengine/bevy-website/pull/109/files#r592758938 decides to not use `#examples`, perhaps this should be aligned with the other links.

2021-04-16 19:29 UTC, cart commented on content/learn/book/getting-started/_index.md
> +4. Try the examples in the [examples folder](https://github.com/bevyengine/bevy/tree/latest/examples)
Yeah i do like directing people to the text content first. Just applied the change.

2021-04-16 19:31 UTC, merged