Fix cursor for corporate tier button
bevyengine/bevy-website pull request #1095
Opened 2024-03-11 21:27 UTC by pkupper

Fixes #1094

2024-03-11 21:55 UTC, NiklasEi commented
Couldn't https://github.com/bevyengine/bevy-website/blob/bfa144bc70c01bd45f9d6fd331cca1ce386187d3/templates/donate.html#L118 be a "real" button element?

2024-03-11 22:13 UTC, TrialDragon commented
Agreed. Using a div for this feels wrong, especially for accessibility given none of the relevant aria elements are implemented (I wouldn't be surprised if the accessibility linter is going to throw a fit when I merge main into branch next). 

This should be a regular `<input>` styled imo.

2024-03-11 22:43 UTC, pkupper commented
Agreed.
When using <button>, some CSS properties have to be set to inherit to maintain the styling. Also, the cursor apparently still needs to be set explicitly. Should these perhaps be set globally for all buttons (e.g. in elements/_button.scss)?

2024-03-11 22:55 UTC, TrialDragon commented
I think it's a safe thing to set the default for buttons to use the pointer cursor. The `.button-square.scss` already does so (tho I don't know where this component is even being used).

2024-03-11 23:07 UTC, TrialDragon requested changes

2024-03-11 23:07 UTC, TrialDragon commented on sass/elements/_button.scss
> +}
```suggestion
}

```
Should be a final newline.

2024-03-11 23:14 UTC, TrialDragon approved these changes

2024-03-12 17:01 UTC, BD103 approved these changes
Thank you!

2024-03-15 14:12 UTC, merged