Add release notes for Gizmos Ui Overlay
bevyengine/bevy-website pull request #1375
Opened 2024-06-08 12:22 UTC by pablo-lua

2024-06-08 12:22 UTC, pablo-lua commented
I'm kinda new to writing release notes, so if you have some suggestion, I'm happy to hear it.

2024-06-10 14:30 UTC, alice-i-cecile commented on release-content/0.14/release-notes/11237_Add_a_gizmobased_overlay_to_show_UI_node_outlines_Adopted.md
> +Ui is a important concept about game design, and as so, the need for a helper tool to help out with layout is increasing.
```suggestion
When working with UI on the web, being able to quickly debug the size of all your boxes is wildly useful.
```

2024-06-10 14:32 UTC, alice-i-cecile requested changes
Example content is good, but the intro could more clearly motivate the feature rather than using vague generalities. This section also really wants a screenshot showing off the feature.

2024-06-10 19:04 UTC, alice-i-cecile approved these changes

2024-06-10 19:18 UTC, merged