Realese Note for #15361: Implement volumetric fog support for both po…
bevyengine/bevy-website pull request #1745
Opened 2024-10-26 09:06 UTC by Soulghost

Fixes #1702

2024-10-27 20:40 UTC, alice-i-cecile commented on release-content/0.15/release-notes/15361_Implement_volumetric_fog_support_for_both_point_lights_and.md
> +Volumetric fog was introduced in Bevy 0.14, where initially, only directional lights could interact with it. In Bevy 0.15, interactions with point lights and spot lights are also supported.
```suggestion
Volumetric fog was [introduced in Bevy 0.14](https://bevyengine.org/news/bevy-0-14/#volumetric-fog-and-volumetric-lighting-light-shafts-god-rays). Initially, only directional lights could interact with it. In Bevy 0.15, point lights and spot lights work with it too.
```

2024-10-27 20:41 UTC, alice-i-cecile requested changes
Small edits, but more importantly I'd really like to have a screenshot for this :) This is one of our few shiny rendering features this release.

2024-10-29 05:50 UTC, Soulghost commented
Hi @alice-i-cecile , I would like to ask for advice on storing the updated volumetric fog screenshot. Should I link to [the existing URL](https://github.com/bevyengine/bevy-website/blob/main/static/screenshots/3D%20Rendering/volumetric_fog.png) and wait for it to update automatically by the GitHub action, or should I place the image elsewhere?

2024-10-29 13:47 UTC, alice-i-cecile commented
This should be stored in the repo: check out the 0.14 release notes for where and how this is done. We should also remove the instruction text from the image for showcase purposes.

2024-10-29 15:02 UTC, Soulghost commented
I have checked the release notes in 0.14 that contain images, both of them use a image path like this:

```
![](filmic_color_grading.jpg)
```

However, the `filmic_color_grading.jpg` is actually located at `content/news/2024-07-04-bevy-0.14/filmic_color_grading.jpg`, not in the same directory as the markdown file. I haven't figure out how the markdown file links to the associated image.

Below is the screenshot without help text. Could you guide me on how to properly link it to the markdown file? Thank you!
![volumetric_fog_with_three_lights](https://github.com/user-attachments/assets/83789ab5-3e55-40f3-acab-8a38fd9cf6af)

2024-11-07 22:08 UTC, mweatherley commented
> Could you guide me on how to properly link it to the markdown file? Thank you!

Now that there is a stub for the actual release notes page, what you'll want to do is merge the `main` branch into your PR branch and put the image into the `content/news/<blah-blah-0.15>` folder. When referencing it in markdown, it will just be `my-image.png` or whatever, where that's the name that you gave it in the folder.

2024-11-15 20:56 UTC, cart approved these changes
I added the image and rebased. Nice work!

2024-11-15 21:33 UTC, merged