Merge and refine UI bundles changes
bevyengine/bevy-website pull request #1815
Opened 2024-11-18 04:21 UTC by alice-i-cecile

Fixes #1767.

2024-11-18 04:44 UTC, richchurcher approved these changes

2024-11-18 07:15 UTC, IQuick143 commented on release-content/0.15/migration-guides/15898_Migrate_UI_bundles_to_required_components.md
> +```diffMove any fields set on `Style` into `Node` and replace all `Style` component usage with `Node`.
This diff seems to be cut in the middle, and also is missing a newline.

2024-11-18 07:15 UTC, IQuick143 commented on release-content/0.15/migration-guides/15898_Migrate_UI_bundles_to_required_components.md
> +      ButtonBundle {
I think it's supposed to continue here.

2024-11-18 07:16 UTC, IQuick143 commented on release-content/0.15/migration-guides/15898_Migrate_UI_bundles_to_required_components.md
> +}
This section is weirdly repeated, is it a Copy-Paste error?

2024-11-19 17:16 UTC, benfrankel requested changes

2024-11-19 17:16 UTC, benfrankel commented on release-content/0.15/migration-guides/15898_Migrate_UI_bundles_to_required_components.md
> +Style {
```suggestion
Node {
```

2024-11-19 17:16 UTC, benfrankel commented on release-content/0.15/migration-guides/15898_Migrate_UI_bundles_to_required_components.md
> +             });
```suggestion
            width: Val::Percent(100.),
            align_items: AlignItems::Center,
            justify_content: JustifyContent::Center,
            ..default()
        });
```

2024-11-19 17:59 UTC, benfrankel approved these changes

2024-11-19 17:59 UTC, benfrankel commented on release-content/0.15/migration-guides/15898_Migrate_UI_bundles_to_required_components.md
> +    width:  Val::Px(100.),
```suggestion
    width: Val::Px(100.),
```

2024-11-19 17:59 UTC, benfrankel commented on release-content/0.15/migration-guides/15898_Migrate_UI_bundles_to_required_components.md
> +    width:  Val::Px(100.),
```suggestion
    width: Val::Px(100.),
```

2024-11-19 19:07 UTC, merged