Bubble and trouble: release notes for bubbling observers
bevyengine/bevy-website pull request #1823
Opened 2024-11-19 22:06 UTC by alice-i-cecile

Fixes https://github.com/bevyengine/bevy-website/issues/1657.

2024-11-19 22:10 UTC, BenjaminBrienen requested changes
Really good!

2024-11-19 22:10 UTC, BenjaminBrienen commented on release-content/0.15/release-notes/13991_Minimal_Bubbling_Observers.md
> +Any type that implements the [`Traversal`] trait can be used as the associated type, and can access arbitrary read-only query data from the world.
```suggestion
Any type that implements the [`Traversal`] trait can be used as the associated type and can access arbitrary read-only query data from the world.
```

"and" is a coordinating conjunction here

2024-11-19 22:23 UTC, BenjaminBrienen approved these changes

2024-11-19 23:00 UTC, aevyrie approved these changes
I think this is missing credit for @NthTensor?.I seem to recall he drove most of this work, though I might be misremembering.

2024-11-20 00:16 UTC, alice-i-cecile commented
Nth is listed as the author here, which is the primary credit :D

2024-11-20 00:50 UTC, merged