Add release notes for box shadows
bevyengine/bevy-website pull request #1827
Opened 2024-11-20 19:10 UTC by alice-i-cecile

Fixes #1721. These notes were developed from the PR description for https://github.com/bevyengine/bevy/pull/15204 :)

2024-11-20 19:30 UTC, richchurcher approved these changes

2024-11-21 02:22 UTC, cart reviewed
Text content is solid, but I think we should render a new "landscape" image. Portrait aspect ratios aren't great for the release notes.

The `box_shadow` example seems reasonable (and the blue is more color-pallet aligned), although it seems like there are some bugs: very hard edges for curves and what appears to be an x-axis scale on some of them). I reworked it slightly:

![image](https://github.com/user-attachments/assets/c932c133-e700-4351-b0fe-e9d765693ec0)

2024-11-21 02:34 UTC, cart commented
New slightly better image that uses @aevyrie's suggestion of a 0.5 "subpixel blur" to clean up the edges on the first row:

![image](https://github.com/user-attachments/assets/ebf11c1b-4ae8-4766-a8c9-a45f6b462c90)

2024-11-21 03:17 UTC, alice-i-cecile commented
Looks nice! I take it you're in the process of a PR for that fix?

2024-11-21 09:39 UTC, ickshonpe commented
Really like these adjustments, looks much better. I don't know about much graphics programming so I concentrated on getting the user API right. With the shader I just went with something simple in the hope that someone else would pick it up and improve the implementation later like this.

2024-11-21 09:48 UTC, ickshonpe commented
> The `box_shadow` example seems reasonable (and the blue is more color-pallet aligned), although it seems like there are some bugs: very hard edges for curves and what appears to be an x-axis scale on some of them). I reworked it slightly:

When the box shadow PR was written, UI anti aliasing was bugged and edges on curves were sharper. If you didn't account for it already, maybe the subpixel blur needs to be turned off if AA is disabled?

2024-11-21 09:52 UTC, ickshonpe approved these changes
Sorry I remember now I said I'd write this myself. Really nice note, no complaints.

2024-11-21 10:22 UTC, ickshonpe requested changes

2024-11-21 10:22 UTC, ickshonpe commented on release-content/0.15/release-notes/15204_box_shadow.md
> +    /// Horizontal difference in size from the occluding uninode
Just noticed this is wrong. The original draft of the PR had separate horizontal and vertical spread values but that would have needed some sort of elliptical border radius support so it was removed but I must have missed this comment in the PR description. From the doc comments for the struct:

```suggestion
    /// How much the shadow should spread outward.
    ///
    /// Negative values will make the shadow shrink inwards.
    /// Percentage values are based on the width of the UI node.
```

2024-11-21 20:54 UTC, cart commented
> Looks nice! I take it you're in the process of a PR for that fix?

This was all done in "userspace" by setting the box shadow blur value to `0.5`. We did discuss clamping values less than 0.5 to 0.5 automatically, but the blur does dirty up clean edges. In the short term I think the fix is to add docs about blur values of 0.5 cleaning up jagged curves. Long term we should consider sorting out a way to automatically anti-alias curves without dirtying up clean vertical and horizontal edges.

2024-11-21 21:03 UTC, cart approved these changes

2024-11-21 21:40 UTC, merged