Only 'build' for pull requests. Build AND deploy for pushes (merges) to master.
bevyengine/bevy-website pull request #24
Opened 2020-08-28 20:44 UTC by CleanCut

I noticed in https://github.com/bevyengine/bevy-website/pull/23 that the CI (luckily) failed to deploy the changed website to production.

Thrashing the web site with deployments from every commit of every pull request is _probably_ not what was intended, so this change makes it so that pull requests only attempt to _build_ the web site, but then merges to master build _and_ deploy the web site.  Pushes straight to master will also still build and deploy.

2020-08-28 20:55 UTC, CleanCut commented
If I'm reading [the CI error](https://github.com/bevyengine/bevy-website/pull/24/checks?check_run_id=1043287955#step:4:8) correctly, the `GITHUB_TOKEN` environment variable is not set in your repo or org Actions settings.

If that environment variable is absent on purpose to prevent pull requests from deploying the web site, then merging this PR should enable you to restore the environment variable safely.

If the environment variable _is_ present, then perhaps GitHub simply does not provide it to CI builds of public forks yet (I know [they do for forks of _private_ repositories](https://github.com/github/roadmap/issues/75)), in which case this change should still be beneficial for those with write access to this repository.

2020-09-02 22:41 UTC, cart requested changes

2020-09-02 22:41 UTC, cart commented on .github/workflows/main.yml
>          TOKEN: ${{secrets.TOKEN}}
can you try changing this to:

```
TOKEN: fake-secret
```

I just tried that and it worked for me.

2020-09-03 00:08 UTC, cart commented
Awesome! I consider this a gap in the zola deploy github action. They shouldn't require a token for non-deployment builds

2020-09-03 00:09 UTC, cart approved these changes

2020-09-03 00:09 UTC, merged

2020-09-03 00:24 UTC, CleanCut commented
Weird! 🤣