Queries section for new book
bevyengine/bevy-website pull request #295
Opened 2022-03-14 18:31 UTC by alice-i-cecile

Ported from #182.

# Status

- [ ] Show, don't tell
- [ ] Revisit and revise

2022-05-14 23:49 UTC, johnnywong1 requested changes

2022-05-14 23:49 UTC, johnnywong1 commented on content/learn/book/ecs/queries/_index.md
> +    player_query: Query<(&Position, &mut Targeting), With<Player>>,
Replace `player_query` with `mut player_query`

2022-05-14 23:49 UTC, johnnywong1 commented on content/learn/book/ecs/queries/_index.md
> +fn take_damage(query: Query<(&mut Life, &mut IncomingDamage)>) {
replace `query` with `mut query`

2022-05-14 23:49 UTC, johnnywong1 commented on content/learn/book/ecs/queries/_index.md
> +fn prepare_fruits(query: Query<(&mut Fruit, Option<&SpecialPreparation>>, Option<&NeedsCooking>)>){
replace `query` with `mut query`

2022-05-14 23:49 UTC, johnnywong1 commented on content/learn/book/ecs/queries/_index.md
> +    target_query: Query<(&mut Defense, &Transform), With<Creature>>) {
replace `target_query` with `mut target_query`

2022-05-14 23:49 UTC, johnnywong1 commented on content/learn/book/ecs/queries/_index.md
> +    camera_query: Query<&mut Transform, With<Camera>>,
replace camera_query with mut camera_query

2022-05-14 23:49 UTC, johnnywong1 commented on content/learn/book/ecs/queries/_index.md
> +    camera_query: Query<&mut Transform, (With<Camera>, Without<Player>)>,
here as well

2022-05-14 23:49 UTC, johnnywong1 commented on content/learn/book/ecs/queries/_index.md
> +    queries: ParamSet<(
not sure if you need it here

2022-05-15 00:11 UTC, alice-i-cecile commented on content/learn/book/ecs/queries/_index.md
> +    player_query: Query<(&Position, &mut Targeting), With<Player>>,
```suggestion
    mut player_query: Query<(&Position, &mut Targeting), With<Player>>,
```

2022-05-15 00:11 UTC, alice-i-cecile commented on content/learn/book/ecs/queries/_index.md
> +fn take_damage(query: Query<(&mut Life, &mut IncomingDamage)>) {
```suggestion
fn take_damage(mut query: Query<(&mut Life, &mut IncomingDamage)>) {
```

2022-05-15 00:11 UTC, alice-i-cecile commented on content/learn/book/ecs/queries/_index.md
> +fn prepare_fruits(query: Query<(&mut Fruit, Option<&SpecialPreparation>>, Option<&NeedsCooking>)>){
```suggestion
fn prepare_fruits(mut query: Query<(&mut Fruit, Option<&SpecialPreparation>>, Option<&NeedsCooking>)>){
```

2022-05-15 00:11 UTC, alice-i-cecile commented on content/learn/book/ecs/queries/_index.md
> +    target_query: Query<(&mut Defense, &Transform), With<Creature>>) {
```suggestion
    mut target_query: Query<(&mut Defense, &Transform), With<Creature>>) {
```

2022-05-15 00:12 UTC, alice-i-cecile commented on content/learn/book/ecs/queries/_index.md
> +    camera_query: Query<&mut Transform, With<Camera>>,
```suggestion
    mut camera_query: Query<&mut Transform, With<Camera>>,
```

2022-05-15 00:12 UTC, alice-i-cecile commented on content/learn/book/ecs/queries/_index.md
> +    camera_query: Query<&mut Transform, (With<Camera>, Without<Player>)>,
```suggestion
    mut camera_query: Query<&mut Transform, (With<Camera>, Without<Player>)>,
```

2022-05-15 00:12 UTC, alice-i-cecile commented on content/learn/book/ecs/queries/_index.md
> +    queries: ParamSet<(
```suggestion
    mut queries: ParamSet<(
```

2023-03-05 00:22 UTC, cart commented
Closing as we will very likely start new PRs (and use this as a reference) when we pick up the new book effort again.

2023-03-05 00:22 UTC, closed without merging