Showcase PlaybackMode in the Bevy 0.11 changelog
bevyengine/bevy-website pull request #733
Opened 2023-08-18 02:49 UTC by hate

Added a snippet to the blog post which mentions the `PlaybackSettings` struct which allows users to manage an audio entity's lifetime.

2023-08-18 02:54 UTC, alice-i-cecile commented on content/news/2023-07-09-bevy-0.11/index.md
> +
```suggestion
```

2023-08-18 02:55 UTC, alice-i-cecile commented on content/news/2023-07-09-bevy-0.11/index.md
> +
```suggestion
```

```

2023-08-18 02:55 UTC, alice-i-cecile commented on content/news/2023-07-09-bevy-0.11/index.md
> +
```suggestion

```

2023-08-18 02:56 UTC, alice-i-cecile approved these changes
We haven't substantively updated these in the past, but this is genuinely useful and well-written. Sure!

2023-08-18 03:01 UTC, alice-i-cecile reviewed
There you go, that looks like it should fix the linter.

2023-08-18 03:01 UTC, alice-i-cecile commented on content/news/2023-07-09-bevy-0.11/index.md
> +```
```suggestion
```

```

2023-08-18 03:01 UTC, alice-i-cecile commented on content/news/2023-07-09-bevy-0.11/index.md
> +[`PlaybackSettings`]: https://docs.rs/bevy/0.11.0/bevy/audio/struct.PlaybackSettings.html
```suggestion
[`PlaybackSettings`]: https://docs.rs/bevy/0.11.0/bevy/audio/struct.PlaybackSettings.html
```

2023-08-18 03:01 UTC, alice-i-cecile commented on content/news/2023-07-09-bevy-0.11/index.md
> +[`PlaybackMode`]: https://docs.rs/bevy/0.11.0/bevy/audio/enum.PlaybackMode.html
```suggestion
[`PlaybackMode`]: https://docs.rs/bevy/0.11.0/bevy/audio/enum.PlaybackMode.html
```

2023-08-18 03:48 UTC, alice-i-cecile requested changes
That code block is no longer closed :)

2023-08-18 04:18 UTC, alice-i-cecile approved these changes

2023-08-19 19:56 UTC, cart approved these changes

2023-08-19 19:57 UTC, cart commented
Needs to pass markdownlint first, but I'm down for "late updates" as a class of changes and this looks good.

2023-08-19 22:35 UTC, alice-i-cecile commented on content/news/2023-07-09-bevy-0.11/index.md
>  Much simpler! To adjust playback you can query for the [`AudioSink`] component:
```suggestion

Much simpler! To adjust playback you can query for the [`AudioSink`] component:
```

2023-08-19 22:36 UTC, alice-i-cecile commented
Alright, that *should* fix the linter. Adding to the merge queue.

2023-08-19 23:01 UTC, merged