0.12: Android suspend and resume
bevyengine/bevy-website pull request #773
Opened 2023-10-20 23:43 UTC by mockersf

Add section for android suspend and resume. This assumes that https://github.com/bevyengine/bevy/pull/10158 will be merged.

If someone can record a better video, it would be very nice. My Android device can't directly record its audio so I have to record it through the microphone

2023-10-26 02:24 UTC, alice-i-cecile approved these changes

2023-10-26 02:24 UTC, alice-i-cecile commented on content/news/2023-10-21-bevy-0.12/index.md
> +On Android, applications are no longer crashing on suspend. Instead, they are paused, and no system
```suggestion
On Android, applications no longer crash on suspend. Instead, they are paused, and no system
```

2023-10-26 02:25 UTC, alice-i-cecile commented on content/news/2023-10-21-bevy-0.12/index.md
> +are running until the application is resumed.
```suggestion
will run until the application is resumed.
```

2023-10-26 02:25 UTC, alice-i-cecile requested changes
Actually, grammar nits are blocking here 😅

2023-10-26 13:11 UTC, alice-i-cecile approved these changes

2023-10-27 02:12 UTC, cart approved these changes

2023-10-27 02:15 UTC, cart approved these changes

2023-10-27 02:15 UTC, merged