0.13: Add Auto Sync Points Section
bevyengine/bevy-website pull request #900
Opened 2024-02-02 06:07 UTC by hymm

For https://github.com/bevyengine/bevy-website/pull/891 announcement post.

2024-02-02 10:40 UTC, Jondolf requested changes

2024-02-02 10:40 UTC, Jondolf commented on content/news/2024-02-03-bevy-0.13/index.md
> +is ordered with another and inserts the apply_deferred for you.
```suggestion
A common scheduling issue is that one system needs to see the effects of the 
commands of another. Before 0.13, you would have to manually insert an 
`apply_deferred` system between the two. Bevy now detects when a system with commands 
is ordered relative to another and inserts the `apply_deferred` for you.
```

2024-02-02 10:40 UTC, Jondolf commented on content/news/2024-02-03-bevy-0.13/index.md
> +    ).chain()
Nit: I think a linter would want a comma here.
```suggestion
    (
        system_with_commands,
        apply_deferred,
        another_system,
    ).chain()
```

2024-02-02 10:40 UTC, Jondolf commented on content/news/2024-02-03-bevy-0.13/index.md
> +    ).chain()
```suggestion
    (
        system_with_commands,
        another_system,
    ).chain()
```

2024-02-02 10:40 UTC, Jondolf commented on content/news/2024-02-03-bevy-0.13/index.md
> +usually be faster.
```suggestion
It also optimizes the automatically inserted `apply_deferred` systems by merging them if 
possible. In most cases, it is recommended to remove all manually inserted 
`apply_deferred` systems, as allowing Bevy to insert and merge these systems as needed will 
usually be faster.
```

2024-02-02 10:40 UTC, Jondolf commented on content/news/2024-02-03-bevy-0.13/index.md
> +There are a several new APIs for opting out of this.
```suggestion
If this new behavior does not work for you, please consult the migration guide. 
There are several new APIs for opting out of this.
```

2024-02-04 18:48 UTC, TrialDragon reviewed
Minor change to the flow of this sentence to make it easier to read.

2024-02-05 00:36 UTC, TrialDragon approved these changes

2024-02-05 00:39 UTC, Jondolf commented on content/news/2024-02-03-bevy-0.13/index.md
>  ## Input for One-Shot Systems
```suggestion
## Input for One-Shot Systems
```

2024-02-05 00:43 UTC, Jondolf approved these changes
LGTM!

2024-02-05 00:46 UTC, Jondolf commented on content/news/2024-02-03-bevy-0.13/index.md
> +A common scheduling issue is that one system needs to see the effects of commands
```suggestion
A common scheduling issue is that one system needs to see the effects of commands
```

2024-02-05 03:23 UTC, hymm commented on content/news/2024-02-03-bevy-0.13/index.md
> +A common scheduling issue is that one system needs to see the effects of commands
Thanks!

2024-02-05 16:03 UTC, alice-i-cecile commented on content/news/2024-02-03-bevy-0.13/index.md
> +is ordered relative to another and inserts the `apply_deferred` for you.
```suggestion
is ordered relative to other systems and inserts the `apply_deferred` for you.
```

2024-02-05 16:04 UTC, alice-i-cecile commented on content/news/2024-02-03-bevy-0.13/index.md
> +There are several new APIs for opting out of this.
```suggestion
There are several new APIs that allow you to opt-out.
```

2024-02-05 16:04 UTC, merged